resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        registerHealthIndicator: true # actuator 정보 노출을 위한 설정
        slidingWindowSize: 10 # sliding window 크기. COUNT_BASED라면 array 크기, TIME_BASED이면 초.
        permittedNumberOfCallsInHalfOpenState: 1 # circuit이 HALF_OPEN 상태일 때 허용되는 call 수이며 해당 call로 들어온 실패율에 따라서 close또는 open으로 변경.
        automatic-transition-from-open-to-half-open-enabled: true # 대기시간이 지난후 서킷을 반열림 상태로 자동 전환할지, 첫번째 호출이 들어오길 기다렸다 반열림 상태로 전환할지.
        waitDurationInOpenState: 10s #열림 상태를 유지하는 시간, 해당 시간이후 반열림 상태로 변경
        failureRateThreshold: 30 #실패한 호출에 대한 임계값(백분율)으로 이 값을 초과하면 서킷이 열림.
        #ringBufferSizeInClosedState: 3 # 닫힘 상태에서의 호출 수로, 서킷을 열어야 할지 결정할 때 사용
        #ringBufferSizeInHalfOpenState: 3 # 반열림 상태에서의 호출 수로, 서킷을 다시 열거나 닫힘 상태로 돌아갈지를 결정할 때 사용
        minimum-number-of-calls: 5 # circuit을 동작시키기 위한 최소한의 call 수
  retry:
    retry-aspect-order: 2 #우선순위를 정해야 retry가 돌고 circuit이 동작.
    configs:
      default:
        maxAttempts: 2
        waitDuration: 1000
        
management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # 테스트를 위해 actuator 전체 노출
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true # circuitbreakers 정보 노출
      
interface:
  test:
    url: http://localhost:8080/api