server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    # rabbitmq target
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:\IntelliJ Projects\msa\natvie-file-repo
        git:
          #git 연동
          uri: https://github.com/inturn86/spring_cloud_config.git
          #private repository 일 경우
          #username : sdf
          #password : 필요.

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh